-- Substitui os códigos genéricos pelos códigos reais da Tabela de Defeitos Venttos Electronics
-- Fonte: Tabela de Códigos de Defeitos / Failure Code Table (revisão 21, 06/11/25)
-- Categorias: CP (Componentes), PL (Placas), AD (Adesivo), SL (Solda),
--             PA (Montagem Final), ICT (Teste ICT), FU (Falhas Funcionais)

DELETE FROM codigo_defeito
WHERE codigo IN (
    'PONTE','FRIA','EXCESSO','SEM_SOLDA','MISS','WRONG','ROT',
    'POLAR','LIFT','DESLOCADO','DANO_COMP','DANO_PCB','OXIDO',
    'CURTO','ABERTO','OUTROS'
);

INSERT INTO codigo_defeito (codigo, descricao, categoria) VALUES
-- ── COMPONENTES ─────────────────────────────────────────────────────────
('CP01', 'Faltando',                    'Componentes'),
('CP02', 'Errado',                      'Componentes'),
('CP03', 'Deslocado',                   'Componentes'),
('CP04', 'Invertido',                   'Componentes'),
('CP05', 'Danificado',                  'Componentes'),
('CP06', 'Oxidado',                     'Componentes'),
('CP07', 'Alto',                        'Componentes'),
('CP08', 'Tombstone',                   'Componentes'),
('CP09', 'Sem Projeção',                'Componentes'),
('CP10', 'Alterado',                    'Componentes'),
('CP11', 'Terminal Dobrado',            'Componentes'),
('CP12', 'Gravação Errada',             'Componentes'),
('CP13', 'Posição Errada',              'Componentes'),
('CP14', 'Valor Errado',                'Componentes'),
('CP15', 'Retrabalho de SMD',           'Componentes'),
('CP16', 'Componente de Lado',          'Componentes'),
('CP17', 'Componente Emborcado',        'Componentes'),
('CP18', 'Mal Encaixado',               'Componentes'),
('CP19', 'Jogado',                      'Componentes'),
('CP20', 'Outros',                      'Componentes'),
('CP21', 'Mal Inserido',                'Componentes'),
('CP22', 'Duplicado',                   'Componentes'),
('CP23', 'Mal Preformado',              'Componentes'),
('CP24', 'Terminal Solto',              'Componentes'),
('CP25', 'Terminal Fora do Padrão',     'Componentes'),
('CP26', 'Componente Extra',            'Componentes'),
('CP27', 'Terminal Longo',              'Componentes'),

-- ── PLACAS (PCB) ────────────────────────────────────────────────────────
('PL01', 'Suja',                        'Placas'),
('PL02', 'Danificada',                  'Placas'),
('PL03', 'Trilha Interrompida',         'Placas'),
('PL04', 'Sem Serigrafia',              'Placas'),
('PL05', 'Falha na Serigrafia',         'Placas'),
('PL06', 'Curto de Impresso',           'Placas'),
('PL07', 'Defeito Não Constatado',      'Placas'),
('PL08', 'Corpo Estranho',              'Placas'),
('PL09', 'Delaminado/Bolha',            'Placas'),
('PL10', 'Excesso de Fluxo',            'Placas'),
('PL11', 'Serigrafia Invertida',        'Placas'),
('PL12', 'Batida',                      'Placas'),
('PL13', 'Outros',                      'Placas'),

-- ── ADESIVO ─────────────────────────────────────────────────────────────
('AD01', 'Faltando',                    'Adesivo'),
('AD02', 'Excesso',                     'Adesivo'),
('AD03', 'Insuficiente',                'Adesivo'),
('AD04', 'Deslocado',                   'Adesivo'),
('AD05', 'No Pad',                      'Adesivo'),
('AD06', 'Outros',                      'Adesivo'),

-- ── SOLDA ───────────────────────────────────────────────────────────────
('SL01', 'Curto',                       'Solda'),
('SL02', 'Ausente',                     'Solda'),
('SL03', 'Insuficiente',                'Solda'),
('SL04', 'Fria',                        'Solda'),
('SL05', 'Embosso',                     'Solda'),
('SL06', 'Não Soldado',                 'Solda'),
('SL07', 'Terminal Solto',              'Solda'),
('SL08', 'Solder Ball',                 'Solda'),
('SL09', 'Outros',                      'Solda'),

-- ── MONTAGEM FINAL ──────────────────────────────────────────────────────
('PA01', 'Tecla Presa',                 'Montagem Final'),
('PA02', 'Risco',                       'Montagem Final'),
('PA03', 'Corpo Estranho',              'Montagem Final'),
('PA04', 'Gabinete Aberto',             'Montagem Final'),
('PA05', 'Parafusos Mal Encaixados',    'Montagem Final'),
('PA06', 'Faltando Etiqueta',           'Montagem Final'),
('PA07', 'Faltando Tampa da Pilha',     'Montagem Final'),
('PA08', 'Quebrado',                    'Montagem Final'),
('PA09', 'Batido',                      'Montagem Final'),
('PA10', 'Falha na Serigrafia',         'Montagem Final'),
('PA11', 'Faltando Ponto de Cola',      'Montagem Final'),
('PA12', 'Serigrafia Invertida',        'Montagem Final'),
('PA13', 'Faltando Serigrafia',         'Montagem Final'),
('PA14', 'Manga',                       'Montagem Final'),
('PA15', 'Falha da Pilha / Não Encaixa','Montagem Final'),
('PA16', 'Mal Parafusado',              'Montagem Final'),
('PA17', 'Faltando Parafuso',           'Montagem Final'),
('PA18', 'Etiqueta Borrada',            'Montagem Final'),
('PA19', 'Etiqueta com Falha',          'Montagem Final'),
('PA20', 'Etiqueta Danificada',         'Montagem Final'),
('PA21', 'Falha de Injeção',            'Montagem Final'),
('PA22', 'Peça Deslocada',              'Montagem Final'),
('PA23', 'Rebarba',                     'Montagem Final'),
('PA24', 'Outros',                      'Montagem Final'),
('PA25', 'Faltando Mola',               'Montagem Final'),
('PA26', 'Mal Encaixado',               'Montagem Final'),

-- ── TESTE ICT ───────────────────────────────────────────────────────────
('ICT001', 'Short Fail',                'ICT'),
('ICT002', 'Comp. Fail',                'ICT'),
('ICT003', 'Open Fail',                 'ICT'),

-- ── FALHAS DE TESTE FUNCIONAL ───────────────────────────────────────────
('FU01',  'Não Liga',                           'Teste Funcional'),
('FU02',  'Não Defende Automaticamente',        'Teste Funcional'),
('FU03',  'Não Inicializa',                     'Teste Funcional'),
('FU04',  'Corrente Alta',                      'Teste Funcional'),
('FU05',  'Corrente Baixa',                     'Teste Funcional'),
('FU06',  'Sem Corrente',                       'Teste Funcional'),
('FU07',  'Sem Imagem HDMI',                    'Teste Funcional'),
('FU08',  'Sem Imagem',                         'Teste Funcional'),
('FU09',  'Não Reconhece USB',                  'Teste Funcional'),
('FU10',  'LED Piscando',                       'Teste Funcional'),
('FU11',  'LED Acendendo Direto',               'Teste Funcional'),
('FU12',  'LED Não Acende',                     'Teste Funcional'),
('FU13',  'Não Acende Todos os LEDs',           'Teste Funcional'),
('FU14',  'Sensor Apaga',                       'Teste Funcional'),
('FU15',  'LED com Luz Fraca',                  'Teste Funcional'),
('FU16',  'LED com Luz Forte',                  'Teste Funcional'),
('FU17',  'Sensor Não Liga Display',            'Teste Funcional'),
('FU18',  'Não Liga Cabo de Rede',              'Teste Funcional'),
('FU19',  'Não Abre Imagem',                    'Teste Funcional'),
('FU20',  'Não Abre Câmera',                    'Teste Funcional'),
('FU21',  'IR Não Atua',                        'Teste Funcional'),
('FU22',  'Sensor Não Atua',                    'Teste Funcional'),
('FU23',  'Tecla Não Atua',                     'Teste Funcional'),
('FU24',  'Teste Travando',                     'Teste Funcional'),
('FU25',  'Display Não Acende',                 'Teste Funcional'),
('FU26',  'Imagem Fixa Colorida',               'Teste Funcional'),
('FU27',  'Imagem Fixa Preto e Branco',         'Teste Funcional'),
('FU28',  'Com Uma Mancha',                     'Teste Funcional'),
('FU29',  'Mancha no Display',                  'Teste Funcional'),
('FU30',  'Falha na Função (RSS Fail)',          'Teste Funcional'),
('FU31',  'Recarrega',                          'Teste Funcional'),
('FU32',  'Imagem Duplicada',                   'Teste Funcional'),
('FU33',  'Não Abre Rádio',                     'Teste Funcional'),
('FU34',  'SSD Não Atua',                       'Teste Funcional'),
('FU35',  'Ponto na Imagem',                    'Teste Funcional'),
('FU36',  'Tecla Foge',                         'Teste Funcional'),
('FU37',  'Vazamento de Ar',                    'Teste Funcional'),
('FU38',  'Tela Suja',                          'Teste Funcional'),
('FU39',  'Tensão Baixa',                       'Teste Funcional'),
('FU40',  'Tensão Alta',                        'Teste Funcional'),
('FU41',  'Outros',                             'Teste Funcional'),
('FU43',  'Tensão Oscilando',                   'Teste Funcional'),
('FU44',  'Bluetooth Não Conecta',              'Teste Funcional'),
('FU45',  'Falha no Movimento',                 'Teste Funcional'),
('FU46',  'Falha de Vibração',                  'Teste Funcional'),
('FU47',  'Falha Elétrico',                     'Teste Funcional'),
('FU48',  'Não Grava Firmware',                 'Teste Funcional'),
('FU49',  'Pré Teste',                          'Teste Funcional'),
('FU50',  'LED RGB',                            'Teste Funcional'),
('FU51',  'Strap',                              'Teste Funcional'),
('FU52',  'Ruído',                              'Teste Funcional'),
('FU53',  'Falha de Violação',                  'Teste Funcional'),
('FU54',  'Botão',                              'Teste Funcional'),
('FU55',  'Sensor de Corrimento',               'Teste Funcional'),
('FU56',  'Memória / Sistema de Arquivos',      'Teste Funcional'),
('FU57',  'Acelerômetro',                       'Teste Funcional'),
('FU58',  'Sensor de Umidade',                  'Teste Funcional'),
('FU60',  'Atualização Não Realizada',          'Teste Funcional'),
('FU61',  'Função BLE Não Atua',                'Teste Funcional'),
('FU62',  'Carga da Bateria',                   'Teste Funcional'),
('FU63',  'Função GPS Não Atua',                'Teste Funcional'),
('FU64',  'Função Modem Não Atua',              'Teste Funcional'),
('FU65',  'Correct Power Down',                 'Teste Funcional'),
('FU67',  'Falha de Reset',                     'Teste Funcional'),
('FU68',  'Falha Ligada na Tela',               'Teste Funcional'),
('FU69',  'Função GPRS Não Atua',               'Teste Funcional'),
('FU70',  'Falha no MAC',                       'Teste Funcional'),
('FU71',  'Falta de Calibração',                'Teste Funcional'),
('FU72',  'Recarregamento',                     'Teste Funcional'),
('FU73',  'Falha na Memória',                   'Teste Funcional'),
('FU74',  'Sem Rádio FM',                       'Teste Funcional'),
('FU75',  'Sem Áudio no Fone',                  'Teste Funcional'),
('FU76',  'Áudio Externo',                      'Teste Funcional'),
('FU77',  'Nenhum Ponto',                       'Teste Funcional'),
('FU79',  'Tela Danificada',                    'Teste Funcional'),
('FU80',  'Falha na Função Impacto',            'Teste Funcional'),
('FU81',  'Não Detecta MAC',                    'Teste Funcional'),
('FU82',  'Falha de Autonomia',                 'Teste Funcional'),
('FU83',  'Cinta Rompida',                      'Teste Funcional'),
('FU84',  'Falha na Função RSSI',               'Teste Funcional'),
('FU85',  'Falha de Gravação do Microfone',     'Teste Funcional'),
('FU86',  'Falha de Leitura do SD Card',        'Teste Funcional'),
('FU88',  'Frequência Oscilando',               'Teste Funcional'),
('FU89',  'Frequência Baixa',                   'Teste Funcional'),
('FU90',  'Falha na Sequência das Cores do LED','Teste Funcional'),
('FU91',  'Ácido / ADC',                        'Teste Funcional'),
('FU92',  'Lente Embaçada',                     'Teste Funcional'),
('FU93',  'Sujo na Tela',                       'Teste Funcional'),
('FU94',  'WiFi Não Atua',                      'Teste Funcional'),
('FU95',  'Consumo de Bateria',                 'Teste Funcional'),
('FU96',  'Sensor de Temperatura',              'Teste Funcional'),
('FU98',  'Corrente Média',                     'Teste Funcional'),
('FU100', 'Test Multivoltagem',                 'Teste Funcional'),
('FU101', 'Chave no Touch',                     'Teste Funcional'),
('FU102', 'Função Intermitente',                'Teste Funcional'),
('FU103', 'Guitarra Não Atua',                  'Teste Funcional'),
('FU104', 'Microfone Não Atua',                 'Teste Funcional'),
('FU105', 'Falha no Display',                   'Teste Funcional'),
('FU106', 'Volume Não Atua',                    'Teste Funcional'),
('FU107', 'Falha de Temperatura',               'Teste Funcional'),
('FU108', 'LED Bicolor',                        'Teste Funcional'),
('FU109', 'Outros / Geral',                     'Teste Funcional'),
('FU110', 'Falha de Antena',                    'Teste Funcional'),
('FU111', 'Não Conecta Bluetooth',              'Teste Funcional')

ON CONFLICT (codigo) DO UPDATE SET
    descricao = EXCLUDED.descricao,
    categoria = EXCLUDED.categoria;
